openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/load_balancers/pools:
    get:
      description: List configured pools.
      operationId: account-load-balancer-pools-list-pools
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
        - in: query
          name: monitor
          schema:
            description: >-
              The ID of the Monitor to use for checking the health of origins
              within this pool.
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/load-balancing_schemas-response_collection
          description: List Pools response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_schemas-response_collection
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: List Pools response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Pools
      tags:
        - Account Load Balancer Pools
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
        - 'Load Balancing: Monitors and Pools Read'
    post:
      description: Create a new pool.
      operationId: account-load-balancer-pools-create-pool
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  $ref: '#/components/schemas/load-balancing_schemas-description'
                enabled:
                  $ref: '#/components/schemas/load-balancing_enabled'
                latitude:
                  $ref: '#/components/schemas/load-balancing_latitude'
                load_shedding:
                  $ref: '#/components/schemas/load-balancing_load_shedding'
                longitude:
                  $ref: '#/components/schemas/load-balancing_longitude'
                minimum_origins:
                  $ref: '#/components/schemas/load-balancing_minimum_origins'
                monitor:
                  $ref: '#/components/schemas/load-balancing_monitor_id'
                name:
                  $ref: '#/components/schemas/load-balancing_name'
                notification_email:
                  $ref: '#/components/schemas/load-balancing_notification_email'
                notification_filter:
                  $ref: '#/components/schemas/load-balancing_notification_filter'
                origin_steering:
                  $ref: '#/components/schemas/load-balancing_origin_steering'
                origins:
                  $ref: '#/components/schemas/load-balancing_origins'
              required:
                - origins
                - name
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-single_response'
          description: Create Pool response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_schemas-single_response
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: Create Pool response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Create Pool
      tags:
        - Account Load Balancer Pools
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
    patch:
      description: >-
        Apply changes to a number of existing pools, overwriting the supplied
        properties. Pools are ordered by ascending `name`. Returns the list of
        affected pools. Supports the standard pagination query parameters,
        either `limit`/`offset` or `per_page`/`page`.
      operationId: account-load-balancer-pools-patch-pools
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                notification_email:
                  $ref: >-
                    #/components/schemas/load-balancing_patch_pools_notification_email
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/load-balancing_schemas-response_collection
          description: Patch Pools response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_schemas-response_collection
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: Patch Pools response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Patch Pools
      tags:
        - Account Load Balancer Pools
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
  /accounts/{account_id}/load_balancers/pools/{pool_id}:
    get:
      description: Fetch a single configured pool.
      operationId: account-load-balancer-pools-pool-details
      parameters:
        - in: path
          name: pool_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-single_response'
          description: Pool Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_schemas-single_response
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: Pool Details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Pool Details
      tags:
        - Account Load Balancer Pools
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
        - 'Load Balancing: Monitors and Pools Read'
    put:
      description: Modify a configured pool.
      operationId: account-load-balancer-pools-update-pool
      parameters:
        - in: path
          name: pool_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                check_regions:
                  $ref: '#/components/schemas/load-balancing_check_regions'
                description:
                  $ref: '#/components/schemas/load-balancing_schemas-description'
                disabled_at:
                  $ref: '#/components/schemas/load-balancing_schemas-disabled_at'
                enabled:
                  $ref: '#/components/schemas/load-balancing_enabled'
                latitude:
                  $ref: '#/components/schemas/load-balancing_latitude'
                load_shedding:
                  $ref: '#/components/schemas/load-balancing_load_shedding'
                longitude:
                  $ref: '#/components/schemas/load-balancing_longitude'
                minimum_origins:
                  $ref: '#/components/schemas/load-balancing_minimum_origins'
                monitor:
                  $ref: '#/components/schemas/load-balancing_monitor_id'
                name:
                  $ref: '#/components/schemas/load-balancing_name'
                notification_email:
                  $ref: '#/components/schemas/load-balancing_notification_email'
                notification_filter:
                  $ref: '#/components/schemas/load-balancing_notification_filter'
                origin_steering:
                  $ref: '#/components/schemas/load-balancing_origin_steering'
                origins:
                  $ref: '#/components/schemas/load-balancing_origins'
              required:
                - origins
                - name
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-single_response'
          description: Update Pool response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_schemas-single_response
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: Update Pool response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Update Pool
      tags:
        - Account Load Balancer Pools
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
    patch:
      description: Apply changes to an existing pool, overwriting the supplied properties.
      operationId: account-load-balancer-pools-patch-pool
      parameters:
        - in: path
          name: pool_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                check_regions:
                  $ref: '#/components/schemas/load-balancing_check_regions'
                description:
                  $ref: '#/components/schemas/load-balancing_schemas-description'
                disabled_at:
                  $ref: '#/components/schemas/load-balancing_schemas-disabled_at'
                enabled:
                  $ref: '#/components/schemas/load-balancing_enabled'
                latitude:
                  $ref: '#/components/schemas/load-balancing_latitude'
                load_shedding:
                  $ref: '#/components/schemas/load-balancing_load_shedding'
                longitude:
                  $ref: '#/components/schemas/load-balancing_longitude'
                minimum_origins:
                  $ref: '#/components/schemas/load-balancing_minimum_origins'
                monitor:
                  $ref: '#/components/schemas/load-balancing_monitor_id'
                name:
                  $ref: '#/components/schemas/load-balancing_name'
                notification_email:
                  $ref: '#/components/schemas/load-balancing_notification_email'
                notification_filter:
                  $ref: '#/components/schemas/load-balancing_notification_filter'
                origin_steering:
                  $ref: '#/components/schemas/load-balancing_origin_steering'
                origins:
                  $ref: '#/components/schemas/load-balancing_origins'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-single_response'
          description: Patch Pool response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_schemas-single_response
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: Patch Pool response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Patch Pool
      tags:
        - Account Load Balancer Pools
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
    delete:
      description: Delete a configured pool.
      operationId: account-load-balancer-pools-delete-pool
      parameters:
        - in: path
          name: pool_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_schemas-id_response'
          description: Delete Pool response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/load-balancing_schemas-id_response'
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: Delete Pool response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Delete Pool
      tags:
        - Account Load Balancer Pools
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
  /accounts/{account_id}/load_balancers/pools/{pool_id}/health:
    get:
      description: Fetch the latest pool health status for a single pool.
      operationId: account-load-balancer-pools-pool-health-details
      parameters:
        - in: path
          name: pool_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_health_details'
          description: Pool Health Details response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/load-balancing_health_details'
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: Pool Health Details response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Pool Health Details
      tags:
        - Account Load Balancer Pools
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
        - 'Load Balancing: Monitors and Pools Read'
  /accounts/{account_id}/load_balancers/pools/{pool_id}/preview:
    post:
      description: >-
        Preview pool health using provided monitor details. The returned
        preview_id can be used in the preview endpoint to retrieve the results.
      operationId: account-load-balancer-pools-preview-pool
      parameters:
        - in: path
          name: pool_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/load-balancing_monitor-editable'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_preview_response'
          description: Preview Pool response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/load-balancing_preview_response'
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: Preview Pool response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: Preview Pool
      tags:
        - Account Load Balancer Pools
  /accounts/{account_id}/load_balancers/pools/{pool_id}/references:
    get:
      description: Get the list of resources that reference the provided pool.
      operationId: account-load-balancer-pools-list-pool-references
      parameters:
        - in: path
          name: pool_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_schemas-identifier'
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_pools-references-response'
          description: List Pool References response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/load-balancing_pools-references-response
                  - $ref: >-
                      #/components/schemas/load-balancing_api-response-common-failure
          description: List Pool References response failure
      security:
        - api_email: []
          api_key: []
          api_token: []
      summary: List Pool References
      tags:
        - Account Load Balancer Pools
      x-api-token-group:
        - 'Load Balancing: Monitors and Pools Write'
        - 'Load Balancing: Monitors and Pools Read'
components:
  schemas:
    load-balancing_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/load-balancing_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/load-balancing_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    load-balancing_check_regions:
      description: >-
        A list of regions from which to run health checks. Null means every
        Cloudflare data center.
      example:
        - WEU
        - ENAM
      items:
        description: >-
          WNAM: Western North America, ENAM: Eastern North America, WEU: Western
          Europe, EEU: Eastern Europe, NSAM: Northern South America, SSAM:
          Southern South America, OC: Oceania, ME: Middle East, NAF: North
          Africa, SAF: South Africa, SAS: Southern Asia, SEAS: South East Asia,
          NEAS: North East Asia, ALL_REGIONS: all regions (ENTERPRISE customers
          only).
        enum:
          - WNAM
          - ENAM
          - WEU
          - EEU
          - NSAM
          - SSAM
          - OC
          - ME
          - NAF
          - SAF
          - SAS
          - SEAS
          - NEAS
          - ALL_REGIONS
        type: string
        x-auditable: true
      nullable: true
      type: array
    load-balancing_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    load-balancing_enabled:
      default: true
      description: >-
        Whether to enable (the default) or disable this pool. Disabled pools
        will not receive traffic and are excluded from health checks. Disabling
        a pool will cause any load balancers using it to failover to the next
        pool (if any).
      example: false
      type: boolean
      x-auditable: true
    load-balancing_health_details:
      allOf:
        - $ref: '#/components/schemas/load-balancing_api-response-single'
        - properties:
            result:
              description: >-
                A list of regions from which to run health checks. Null means
                every Cloudflare data center.
              example:
                pool_id: 17b5962d775c646f3f9725cbc7a53df4
                pop_health:
                  Amsterdam, NL:
                    healthy: true
                    origins:
                      - 2001:DB8::5:
                          failure_reason: No failures
                          healthy: true
                          response_code: 401
                          rtt: 12.1ms
              properties:
                pool_id:
                  description: Pool ID
                  example: 17b5962d775c646f3f9725cbc7a53df4
                  type: string
                  x-auditable: true
                pop_health:
                  description: List of regions and associated health status.
                  properties:
                    healthy:
                      description: Whether health check in region is healthy.
                      example: true
                      type: boolean
                      x-auditable: true
                    origins:
                      items:
                        $ref: '#/components/schemas/load-balancing_origin-health'
                      type: array
                  type: object
              type: object
    load-balancing_latitude:
      description: >-
        The latitude of the data center containing the origins used in this pool
        in decimal degrees. If this is set, longitude must also be set.
      type: number
      x-auditable: true
    load-balancing_load_shedding:
      description: Configures load shedding policies and percentages for the pool.
      properties:
        default_percent:
          default: 0
          description: >-
            The percent of traffic to shed from the pool, according to the
            default policy. Applies to new sessions and traffic without session
            affinity.
          maximum: 100
          minimum: 0
          type: number
          x-auditable: true
        default_policy:
          default: random
          description: >-
            The default policy to use when load shedding. A random policy
            randomly sheds a given percent of requests. A hash policy computes a
            hash over the CF-Connecting-IP address and sheds all requests
            originating from a percent of IPs.
          enum:
            - random
            - hash
          type: string
          x-auditable: true
        session_percent:
          default: 0
          description: >-
            The percent of existing sessions to shed from the pool, according to
            the session policy.
          maximum: 100
          minimum: 0
          type: number
          x-auditable: true
        session_policy:
          default: hash
          description: >-
            Only the hash policy is supported for existing sessions (to avoid
            exponential decay).
          enum:
            - hash
          type: string
          x-auditable: true
      type: object
    load-balancing_longitude:
      description: >-
        The longitude of the data center containing the origins used in this
        pool in decimal degrees. If this is set, latitude must also be set.
      type: number
      x-auditable: true
    load-balancing_minimum_origins:
      default: 1
      description: >-
        The minimum number of origins that must be healthy for this pool to
        serve traffic. If the number of healthy origins falls below this number,
        the pool will be marked unhealthy and will failover to the next
        available pool.
      type: integer
      x-auditable: true
    load-balancing_monitor-editable:
      properties:
        allow_insecure:
          $ref: '#/components/schemas/load-balancing_allow_insecure'
        consecutive_down:
          $ref: '#/components/schemas/load-balancing_consecutive_down'
        consecutive_up:
          $ref: '#/components/schemas/load-balancing_consecutive_up'
        description:
          $ref: '#/components/schemas/load-balancing_description'
        expected_body:
          $ref: '#/components/schemas/load-balancing_expected_body'
        expected_codes:
          $ref: '#/components/schemas/load-balancing_expected_codes'
        follow_redirects:
          $ref: '#/components/schemas/load-balancing_follow_redirects'
        header:
          $ref: '#/components/schemas/load-balancing_header'
        interval:
          $ref: '#/components/schemas/load-balancing_interval'
        method:
          $ref: '#/components/schemas/load-balancing_method'
        path:
          $ref: '#/components/schemas/load-balancing_path'
        port:
          $ref: '#/components/schemas/load-balancing_port'
        probe_zone:
          $ref: '#/components/schemas/load-balancing_probe_zone'
        retries:
          $ref: '#/components/schemas/load-balancing_retries'
        timeout:
          $ref: '#/components/schemas/load-balancing_timeout'
        type:
          $ref: '#/components/schemas/load-balancing_type'
      type: object
    load-balancing_monitor_id:
      description: >-
        The ID of the Monitor to use for checking the health of origins within
        this pool.
      type: string
      x-auditable: true
    load-balancing_name:
      description: >-
        A short name (tag) for the pool. Only alphanumeric characters, hyphens,
        and underscores are allowed.
      example: primary-dc-1
      type: string
      x-auditable: true
    load-balancing_notification_email:
      description: >-
        This field is now deprecated. It has been moved to Cloudflare's
        Centralized Notification service
        https://developers.cloudflare.com/fundamentals/notifications/. The email
        address to send health status notifications to. This can be an
        individual mailbox or a mailing list. Multiple emails can be supplied as
        a comma delimited list.
      example: someone@example.com,sometwo@example.com
      type: string
      x-auditable: true
    load-balancing_notification_filter:
      description: >-
        Filter pool and origin health notifications by resource type or health
        status. Use null to reset.
      example:
        origin:
          disable: true
        pool:
          healthy: false
      nullable: true
      properties:
        origin:
          $ref: '#/components/schemas/load-balancing_filter_options'
        pool:
          $ref: '#/components/schemas/load-balancing_filter_options'
      type: object
    load-balancing_origin_steering:
      description: >-
        Configures origin steering for the pool. Controls how origins are
        selected for new sessions and traffic without session affinity.
      properties:
        policy:
          default: random
          description: >-
            The type of origin steering policy to use.

            - `"random"`: Select an origin randomly.

            - `"hash"`: Select an origin by computing a hash over the
            CF-Connecting-IP address.

            - `"least_outstanding_requests"`: Select an origin by taking into
            consideration origin weights, as well as each origin's number of
            outstanding requests. Origins with more pending requests are
            weighted proportionately less relative to others.

            - `"least_connections"`: Select an origin by taking into
            consideration origin weights, as well as each origin's number of
            open connections. Origins with more open connections are weighted
            proportionately less relative to others. Supported for HTTP/1 and
            HTTP/2 connections.
          enum:
            - random
            - hash
            - least_outstanding_requests
            - least_connections
          type: string
          x-auditable: true
      type: object
    load-balancing_origins:
      description: >-
        The list of origins within this pool. Traffic directed at this pool is
        balanced across all currently healthy origins, provided the pool itself
        is healthy.
      items:
        $ref: '#/components/schemas/load-balancing_origin'
      type: array
    load-balancing_patch_pools_notification_email:
      description: >-
        The email address to send health status notifications to. This field is
        now deprecated in favor of Cloudflare Notifications for Load Balancing,
        so only resetting this field with an empty string `""` is accepted.
      enum:
        - ''
      example: ''
      type: string
    load-balancing_pools-references-response:
      allOf:
        - $ref: '#/components/schemas/load-balancing_api-response-common'
        - properties:
            result:
              description: List of resources that reference a given pool.
              example:
                - reference_type: referrer
                  resource_id: 699d98642c564d2e855e9661899b7252
                  resource_name: www.example.com
                  resource_type: load_balancer
                - reference_type: referral
                  resource_id: f1aba936b94213e5b8dca0c0dbf1f9cc
                  resource_name: Login page monitor
                  resource_type: monitor
              items:
                properties:
                  reference_type:
                    enum:
                      - '*'
                      - referral
                      - referrer
                    type: string
                    x-auditable: true
                  resource_id:
                    type: string
                    x-auditable: true
                  resource_name:
                    type: string
                    x-auditable: true
                  resource_type:
                    type: string
                    x-auditable: true
                type: object
              type: array
    load-balancing_preview_response:
      allOf:
        - $ref: '#/components/schemas/load-balancing_api-response-single'
        - properties:
            result:
              properties:
                pools:
                  additionalProperties:
                    description: The pool name associated with the pool ID.
                    type: string
                    x-auditable: true
                  description: Monitored pool IDs mapped to their respective names.
                  example:
                    abwlnp5jbqn45ecgxd03erbgtxtqai0d: WNAM Datacenter
                    ve8h9lrcip5n5bbga9yqmdws28ay5d0l: EEU Datacenter
                  type: object
                preview_id:
                  $ref: '#/components/schemas/load-balancing_identifier'
              type: object
    load-balancing_schemas-description:
      description: A human-readable description of the pool.
      example: Primary data center - Provider XYZ
      type: string
      x-auditable: true
    load-balancing_schemas-disabled_at:
      description: >-
        This field shows up only if the pool is disabled. This field is set with
        the time the pool was disabled at.
      format: date-time
      readOnly: true
      type: string
      x-auditable: true
    load-balancing_schemas-id_response:
      allOf:
        - $ref: '#/components/schemas/load-balancing_api-response-single'
        - properties:
            result:
              properties:
                id:
                  $ref: '#/components/schemas/load-balancing_schemas-identifier'
              type: object
    load-balancing_schemas-identifier:
      example: 17b5962d775c646f3f9725cbc7a53df4
      type: string
      x-auditable: true
    load-balancing_schemas-response_collection:
      allOf:
        - $ref: >-
            #/components/schemas/load-balancing_api-paginated-response-collection
        - properties:
            result:
              items:
                $ref: '#/components/schemas/load-balancing_pool'
              type: array
    load-balancing_schemas-single_response:
      allOf:
        - $ref: '#/components/schemas/load-balancing_api-response-single'
        - properties:
            result:
              $ref: '#/components/schemas/load-balancing_pool'
