openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/settings/ssl_automatic_mode:
    get:
      description: >-
        If the system is enabled, the response will include next_scheduled_scan,
        representing the next time this zone will be scanned and the zone's
        ssl/tls encryption mode is potentially upgraded by the system. If the
        system is disabled, next_scheduled_scan will not be present in the
        response body.
      operationId: ssl-detector-automatic-mode-get-enrollment
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/cache_identifier'
      responses:
        '200':
          content:
            application/json:
              examples:
                Disabled:
                  $ref: >-
                    #/components/examples/cache_dummy_automatic_upgrader_enabled_response
                Enabled:
                  $ref: >-
                    #/components/examples/cache_dummy_automatic_upgrader_disabled_response
              schema:
                $ref: '#/components/schemas/cache_api-response-single-id'
          description: Get Automatic SSL/TLS Enrollment status response.
        4XX:
          content:
            application/json:
              examples:
                Error:
                  $ref: '#/components/examples/cache_dummy_error_response'
              schema:
                $ref: '#/components/schemas/cache_api-response-common-failure'
          description: Get Automatic SSL/TLS Enrollment status failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Automatic SSL/TLS enrollment status for the given zone
      tags:
        - Automatic SSL/TLS
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
        - SSL and Certificates Write
        - SSL and Certificates Read
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: >-
        The automatic system is enabled when this endpoint is hit with value in
        the request body is set to "auto", and disabled when the request body
        value is set to "custom".
      operationId: ssl-detector-automatic-mode-patch-enrollment
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/cache_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cache_schemas_patch'
        required: true
      responses:
        '200':
          content:
            application/json:
              examples:
                Enabled:
                  $ref: >-
                    #/components/examples/cache_dummy_automatic_upgrader_enabled_response
              schema:
                $ref: '#/components/schemas/cache_api-response-single-id'
          description: Patch Automatic SSL/TLS Enrollment status response.
        4XX:
          content:
            application/json:
              examples:
                Error:
                  $ref: '#/components/examples/cache_dummy_error_response'
              schema:
                $ref: '#/components/schemas/cache_api-response-common-failure'
          description: Patch Automatic SSL/TLS Enrollment status failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Patch Automatic SSL/TLS Enrollment status for given zone
      tags:
        - Automatic SSL/TLS
      x-api-token-group:
        - Zone Settings Write
        - SSL and Certificates Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
          - '#zone_settings:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    cache_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/cache_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/cache_messages'
          example: []
        result:
          $ref: '#/components/schemas/cache_result'
        success:
          description: Indicates the API call's success or failure.
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    cache_api-response-single-id:
      properties:
        errors:
          $ref: '#/components/schemas/cache_messages'
        messages:
          $ref: '#/components/schemas/cache_messages'
        result:
          $ref: '#/components/schemas/cache_result'
        success:
          description: Indicates the API call's success or failure.
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    cache_identifier:
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    cache_schemas_patch:
      description: Update enablement of Automatic SSL/TLS.
      properties:
        value:
          $ref: '#/components/schemas/cache_schemas_value'
      required:
        - value
      type: object
  examples:
    cache_dummy_automatic_upgrader_disabled_response:
      value:
        errors: []
        messages: []
        result:
          editable: true
          id: ssl_automatic_mode
          modified_on: '2014-01-01T05:20:00.12345Z'
          value: custom
        success: true
    cache_dummy_automatic_upgrader_enabled_response:
      value:
        errors: []
        messages: []
        result:
          editable: true
          id: ssl_automatic_mode
          modified_on: '2014-01-01T05:20:00.12345Z'
          next_scheduled_scan: '2014-02-01T05:20:00.12345Z'
          value: auto
        success: true
    cache_dummy_error_response:
      value:
        errors:
          - code: 1008
            message: >-
              Invalid SSL/TLS encryption configuration value, only auto or
              custom accepted
        messages: []
        result:
          editable: true
          id: ssl_automatic_mode
          modified_on: '2014-01-01T05:20:00.12345Z'
          value: custom
        success: false
