openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/bot_management:
    get:
      description: Retrieve a zone's Bot Management Config
      operationId: bot-management-for-a-zone-get-config
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/bot-management_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/bot-management_bot_management_response_body
          description: Bot Management config response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/bot-management_bot_management_response_body
                  - $ref: >-
                      #/components/schemas/bot-management_api-response-common-failure
          description: Bot Management config response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Zone Bot Management Config
      tags:
        - Bot Settings
      x-api-token-group:
        - Bot Management Write
        - Bot Management Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    put:
      description: >
        Updates the Bot Management configuration for a zone.


        This API is used to update:

        - **Bot Fight Mode**

        - **Super Bot Fight Mode**

        - **Bot Management for Enterprise**


        See [Bot Plans](https://developers.cloudflare.com/bots/plans/) for more
        information on the different plans 

        \

        If you recently upgraded or downgraded your plan, refer to the following
        examples to clean up old configurations. 

        Copy and paste the example body to remove old zone configurations based
        on your current plan.

        #### Clean up configuration for Bot Fight Mode plan

        ```json

        {
          "sbfm_likely_automated": "allow", 
          "sbfm_definitely_automated": "allow", 
          "sbfm_verified_bots": "allow", 
          "sbfm_static_resource_protection": false, 
          "optimize_wordpress": false, 
          "suppress_session_score": false 
        }

        ```

        #### Clean up configuration for SBFM Pro plan

        ```json

        {
          "sbfm_likely_automated": "allow", 
          "fight_mode": false 
        }

        ```

        #### Clean up configuration for SBFM Biz plan

        ```json

        {
          "fight_mode": false
        }

        ```

        #### Clean up configuration for BM Enterprise Subscription plan

        It is strongly recommended that you ensure you have [custom
        rules](https://developers.cloudflare.com/waf/custom-rules/) in place to
        protect your zone before disabling the SBFM rules. Without these
        protections, your zone is vulnerable to attacks.

        ```json

        {
          "sbfm_likely_automated": "allow", 
          "sbfm_definitely_automated": "allow", 
          "sbfm_verified_bots": "allow", 
          "sbfm_static_resource_protection": false, 
          "optimize_wordpress": false, 
          "fight_mode": false
        }

        ```
      operationId: bot-management-for-a-zone-update-config
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/bot-management_identifier'
      requestBody:
        content:
          application/json:
            examples:
              example1:
                summary: Bot Fight Mode default example
                value:
                  ai_bots_protection: disabled
                  crawler_protection: disabled
                  enable_js: true
                  fight_mode: true
              example2:
                summary: SBFM Pro plan default example
                value:
                  ai_bots_protection: disabled
                  crawler_protection: disabled
                  enable_js: true
                  sbfm_definitely_automated: block
                  sbfm_static_resource_protection: true
                  sbfm_verified_bots: block
              example3:
                summary: SBFM Biz plan default example
                value:
                  ai_bots_protection: disabled
                  crawler_protection: disabled
                  enable_js: true
                  sbfm_definitely_automated: block
                  sbfm_likely_automated: managed_challenge
                  sbfm_static_resource_protection: true
                  sbfm_verified_bots: block
              example4:
                summary: BM Enterprise Subscription default example
                value:
                  ai_bots_protection: disabled
                  auto_update_model: true
                  crawler_protection: disabled
                  enable_js: true
              example5:
                summary: Clean up configuration for Bot Fight Mode plan
                value:
                  optimize_wordpress: false
                  sbfm_definitely_automated: allow
                  sbfm_likely_automated: allow
                  sbfm_static_resource_protection: false
                  sbfm_verified_bots: allow
                  suppress_session_score: false
              example6:
                summary: Clean up configuration for SBFM Pro plan
                value:
                  fight_mode: false
                  sbfm_likely_automated: allow
              example7:
                summary: Clean up configuration for SBFM Biz plan
                value:
                  fight_mode: false
              example8:
                summary: Clean up configuration for BM Enterprise Subscription
                value:
                  fight_mode: false
                  optimize_wordpress: false
                  sbfm_definitely_automated: allow
                  sbfm_likely_automated: allow
                  sbfm_static_resource_protection: false
                  sbfm_verified_bots: allow
              example9:
                summary: Block AI Bots on Ad pages only
                value:
                  ai_bots_protection: only_on_ad_pages
            schema:
              $ref: '#/components/schemas/bot-management_config_single'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/bot-management_bot_management_response_body
          description: Update Bot Management response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/bot-management_bot_management_response_body
                  - $ref: >-
                      #/components/schemas/bot-management_api-response-common-failure
          description: Update Bot Management response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Update Zone Bot Management Config
      tags:
        - Bot Settings
      x-api-token-group:
        - Bot Management Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    bot-management_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/bot-management_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/bot-management_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    bot-management_bot_management_response_body:
      allOf:
        - $ref: '#/components/schemas/bot-management_api-response-single'
        - properties:
            result:
              oneOf:
                - $ref: '#/components/schemas/bot-management_bot_fight_mode_config'
                - $ref: '#/components/schemas/bot-management_sbfm_definitely_config'
                - $ref: '#/components/schemas/bot-management_sbfm_likely_config'
                - $ref: '#/components/schemas/bot-management_bm_subscription_config'
          type: object
    bot-management_config_single:
      oneOf:
        - $ref: '#/components/schemas/bot-management_bot_fight_mode_config'
        - $ref: '#/components/schemas/bot-management_sbfm_definitely_config'
        - $ref: '#/components/schemas/bot-management_sbfm_likely_config'
        - $ref: '#/components/schemas/bot-management_bm_subscription_config'
      type: object
    bot-management_identifier:
      description: Identifier.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
