openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /accounts/{account_id}/vectorize/v2/indexes:
    get:
      description: Returns a list of Vectorize Indexes
      operationId: vectorize-list-vectorize-indexes
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-common'
                  - properties:
                      result:
                        items:
                          $ref: '#/components/schemas/vectorize_create-index-response'
                        type: array
          description: List Vectorize Index Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: List Vectorize Index Failure Response
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Vectorize Indexes
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
        - Vectorize Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.vectorize.index.list
    post:
      description: Creates and returns a new Vectorize Index.
      operationId: vectorize-create-vectorize-index
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vectorize_create-index-request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/vectorize_create-index-response'
          description: Create Vectorize Index Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Create Vectorize Index Failure Response
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create Vectorize Index
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.vectorize.index.create
  /accounts/{account_id}/vectorize/v2/indexes/{index_name}:
    get:
      description: Returns the specified Vectorize Index.
      operationId: vectorize-get-vectorize-index
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/vectorize_create-index-response'
          description: Get Vectorize Index Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Get Vectorize Index Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Vectorize Index
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
        - Vectorize Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.vectorize.index.read
    delete:
      description: Deletes the specified Vectorize Index.
      operationId: vectorize-delete-vectorize-index
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        nullable: true
                        type: object
          description: Delete Vectorize Index Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Delete Vectorize Index Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Delete Vectorize Index
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.vectorize.index.delete
  /accounts/{account_id}/vectorize/v2/indexes/{index_name}/delete_by_ids:
    post:
      description: Delete a set of vectors from an index by their vector identifiers.
      operationId: vectorize-delete-vectors-by-id
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/vectorize_index-delete-vectors-by-id-request
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: >-
                          #/components/schemas/vectorize_index-delete-vectors-by-id-v2-response
          description: Delete Vector Identifiers Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Delete Vector Identifiers Failure Response
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Delete Vectors By Identifier
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.vectorize.index.delete
  /accounts/{account_id}/vectorize/v2/indexes/{index_name}/get_by_ids:
    post:
      description: Get a set of vectors from an index by their vector identifiers.
      operationId: vectorize-get-vectors-by-id
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vectorize_index-get-vectors-by-id-request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: >-
                          #/components/schemas/vectorize_index-get-vectors-by-id-response
          description: Get Vectors By Identifier Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Get Vectors By Identifier Failure Response
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Vectors By Identifier
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
        - Vectorize Read
  /accounts/{account_id}/vectorize/v2/indexes/{index_name}/info:
    get:
      description: Get information about a vectorize index.
      operationId: vectorize-index-info
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/vectorize_index-info-response'
          description: Get Vectorize Index Info Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Get Vectorize Index Info Failure Response
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Vectorize Index Info
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
        - Vectorize Read
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.vectorize.index.read
  /accounts/{account_id}/vectorize/v2/indexes/{index_name}/insert:
    post:
      description: >-
        Inserts vectors into the specified index and returns a mutation id
        corresponding to the vectors enqueued for insertion.
      operationId: vectorize-insert-vector
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
        - in: query
          name: unparsable-behavior
          schema:
            description: Behavior for ndjson parse failures.
            enum:
              - error
              - discard
            type: string
      requestBody:
        content:
          application/x-ndjson:
            schema:
              description: ndjson file containing vectors to insert.
              example: '@/path/to/vectors.ndjson'
              type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: >-
                          #/components/schemas/vectorize_index-insert-v2-response
          description: Insert Vectors Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Insert Vectors Failure Response
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Insert Vectors
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
  /accounts/{account_id}/vectorize/v2/indexes/{index_name}/metadata_index/create:
    post:
      description: >-
        Enable metadata filtering based on metadata property. Limited to 10
        properties.
      operationId: vectorize-create-metadata-index
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vectorize_create-metadata-index-request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: >-
                          #/components/schemas/vectorize_create-metadata-index-response
          description: Create Metadata Index Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Create Metadata Index Failure Response
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Create Metadata Index
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.vectorize.index.create
  /accounts/{account_id}/vectorize/v2/indexes/{index_name}/metadata_index/delete:
    post:
      description: Allow Vectorize to delete the specified metadata index.
      operationId: vectorize-delete-metadata-index
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vectorize_delete-metadata-index-request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: >-
                          #/components/schemas/vectorize_delete-metadata-index-response
          description: Delete Metadata Index Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Delete Metadata Index Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Delete Metadata Index
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
      x-cfPermissionsRequired:
        enum:
          - com.cloudflare.edge.vectorize.index.delete
  /accounts/{account_id}/vectorize/v2/indexes/{index_name}/metadata_index/list:
    get:
      description: List Metadata Indexes for the specified Vectorize Index.
      operationId: vectorize-list-metadata-indexes
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: >-
                          #/components/schemas/vectorize_list-metadata-index-response
          description: List Metadata Index Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: List Metadata Index Failure Response
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Metadata Indexes
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
        - Vectorize Read
  /accounts/{account_id}/vectorize/v2/indexes/{index_name}/query:
    post:
      description: Finds vectors closest to a given vector in an index.
      operationId: vectorize-query-vector
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vectorize_index-query-v2-request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/vectorize_index-query-v2-response'
          description: Query Vectors Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Query Vectors Failure Response
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Query Vectors
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
        - Vectorize Read
  /accounts/{account_id}/vectorize/v2/indexes/{index_name}/upsert:
    post:
      description: >-
        Upserts vectors into the specified index, creating them if they do not
        exist and returns a mutation id corresponding to the vectors enqueued
        for upsertion.
      operationId: vectorize-upsert-vector
      parameters:
        - in: path
          name: account_id
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_identifier'
        - in: path
          name: index_name
          required: true
          schema:
            $ref: '#/components/schemas/vectorize_index-name'
        - in: query
          name: unparsable-behavior
          schema:
            description: Behavior for ndjson parse failures.
            enum:
              - error
              - discard
            type: string
      requestBody:
        content:
          application/x-ndjson:
            schema:
              description: ndjson file containing vectors to upsert.
              example: '@/path/to/vectors.ndjson'
              type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/vectorize_api-response-single'
                  - properties:
                      result:
                        $ref: >-
                          #/components/schemas/vectorize_index-upsert-v2-response
          description: Upsert Vectors Response
        4XX:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/vectorize_api-response-single'
                      - properties:
                          result:
                            nullable: true
                            type: object
                        type: object
                  - $ref: '#/components/schemas/vectorize_api-response-common-failure'
          description: Upsert Vectors Failure Response
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Upsert Vectors
      tags:
        - Vectorize
      x-api-token-group:
        - Vectorize Write
components:
  schemas:
    vectorize_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/vectorize_messages'
        messages:
          $ref: '#/components/schemas/vectorize_messages'
        result:
          anyOf:
            - type: object
            - items: {}
              type: array
            - type: string
        success:
          description: Whether the API call was successful
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    vectorize_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/vectorize_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/vectorize_messages'
          example: []
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    vectorize_api-response-single:
      allOf:
        - $ref: '#/components/schemas/vectorize_api-response-common'
        - properties:
            result:
              anyOf:
                - type: object
                - type: string
              nullable: true
              type: object
      type: object
    vectorize_create-index-request:
      properties:
        config:
          allOf:
            - $ref: '#/components/schemas/vectorize_index-configuration'
        description:
          $ref: '#/components/schemas/vectorize_index-description'
        name:
          $ref: '#/components/schemas/vectorize_index-name'
      required:
        - name
        - config
      type: object
    vectorize_create-index-response:
      properties:
        config:
          $ref: '#/components/schemas/vectorize_index-dimension-configuration'
        created_on:
          description: >-
            Specifies the timestamp the resource was created as an ISO8601
            string.
          example: '2022-11-15T18:25:44.442097Z'
          format: date-time
          readOnly: true
          type: string
          x-auditable: true
        description:
          $ref: '#/components/schemas/vectorize_index-description'
        modified_on:
          description: >-
            Specifies the timestamp the resource was modified as an ISO8601
            string.
          example: '2022-11-15T18:25:44.442097Z'
          format: date-time
          readOnly: true
          type: string
          x-auditable: true
        name:
          $ref: '#/components/schemas/vectorize_index-name'
      type: object
    vectorize_create-metadata-index-request:
      properties:
        indexType:
          description: Specifies the type of metadata property to index.
          enum:
            - string
            - number
            - boolean
          type: string
          x-auditable: true
        propertyName:
          description: Specifies the metadata property to index.
          example: random_metadata_property
          type: string
          x-auditable: true
      required:
        - propertyName
        - indexType
      type: object
    vectorize_create-metadata-index-response:
      properties:
        mutationId:
          $ref: '#/components/schemas/vectorize_mutation-uuid'
      type: object
    vectorize_delete-metadata-index-request:
      properties:
        propertyName:
          description: Specifies the metadata property for which the index must be deleted.
          example: random_metadata_property
          type: string
          x-auditable: true
      required:
        - propertyName
      type: object
    vectorize_delete-metadata-index-response:
      properties:
        mutationId:
          $ref: '#/components/schemas/vectorize_mutation-uuid'
      type: object
    vectorize_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    vectorize_index-delete-vectors-by-id-request:
      properties:
        ids:
          description: >-
            A list of vector identifiers to delete from the index indicated by
            the path.
          example:
            - 5121db81354a40c6aedc3fe1ace51c59
            - f90eb49c2107486abdfd78c67e853430
          items:
            $ref: '#/components/schemas/vectorize_vector-identifier'
          type: array
      type: object
    vectorize_index-delete-vectors-by-id-v2-response:
      properties:
        mutationId:
          $ref: '#/components/schemas/vectorize_mutation-uuid'
      type: object
    vectorize_index-get-vectors-by-id-request:
      properties:
        ids:
          description: >-
            A list of vector identifiers to retrieve from the index indicated by
            the path.
          example:
            - 5121db81354a40c6aedc3fe1ace51c59
            - f90eb49c2107486abdfd78c67e853430
          items:
            $ref: '#/components/schemas/vectorize_vector-identifier'
          type: array
      type: object
    vectorize_index-get-vectors-by-id-response:
      description: Array of vectors with matching ids.
      example:
        - id: some-vector-id
          metadata:
            another-key: another-value
            customer-id: 442
          values:
            - 0.812
            - 0.621
            - 0.261
        - id: other-vector-id
          metadata:
            another-key: with-a-value
            customer-id: 2151
          namespace: namespaced
          values:
            - 0.961
            - 0.751
            - 0.661
      items:
        properties:
          id:
            $ref: '#/components/schemas/vectorize_vector-identifier'
          metadata:
            type: object
          namespace:
            nullable: true
            type: string
          values:
            items:
              type: number
            type: array
        type: object
      type: array
    vectorize_index-info-response:
      properties:
        dimensions:
          $ref: '#/components/schemas/vectorize_index-dimensions'
        processedUpToDatetime:
          description: >-
            Specifies the timestamp the last mutation batch was processed as an
            ISO8601 string.
          example: '2024-07-22T18:25:44.442097Z'
          format: date-time
          nullable: true
          readOnly: true
          type: string
          x-auditable: true
        processedUpToMutation:
          $ref: '#/components/schemas/vectorize_mutation-uuid'
        vectorCount:
          description: Specifies the number of vectors present in the index
          example: 300000
          type: integer
          x-auditable: true
      type: object
    vectorize_index-insert-v2-response:
      properties:
        mutationId:
          $ref: '#/components/schemas/vectorize_mutation-uuid'
      type: object
    vectorize_index-name:
      example: example-index
      pattern: ^([a-z]+[a-z0-9_-]*[a-z0-9]+)$
      type: string
      x-auditable: true
    vectorize_index-query-v2-request:
      properties:
        filter:
          description: A metadata filter expression used to limit nearest neighbor results.
          example:
            has_viewed:
              $ne: true
            streaming_platform: netflix
          type: object
        returnMetadata:
          default: none
          description: >-
            Whether to return no metadata, indexed metadata or all metadata
            associated with the closest vectors.
          enum:
            - none
            - indexed
            - all
          type: string
        returnValues:
          default: false
          description: Whether to return the values associated with the closest vectors.
          type: boolean
        topK:
          default: 5
          description: The number of nearest neighbors to find.
          example: 5
          type: number
        vector:
          description: The search vector that will be used to find the nearest neighbors.
          example:
            - 0.5
            - 0.5
            - 0.5
          items:
            type: number
          type: array
      required:
        - vector
      type: object
    vectorize_index-query-v2-response:
      properties:
        count:
          description: Specifies the count of vectors returned by the search
          type: integer
        matches:
          description: Array of vectors matched by the search
          items:
            properties:
              id:
                $ref: '#/components/schemas/vectorize_vector-identifier'
              metadata:
                nullable: true
                type: object
              namespace:
                nullable: true
                type: string
              score:
                description: >-
                  The score of the vector according to the index's distance
                  metric
                type: number
              values:
                items:
                  type: number
                nullable: true
                type: array
            type: object
          type: array
      type: object
    vectorize_index-upsert-v2-response:
      properties:
        mutationId:
          $ref: '#/components/schemas/vectorize_mutation-uuid'
      type: object
    vectorize_list-metadata-index-response:
      example:
        metadataIndexes:
          - indexType: number
            propertyName: some-num-prop
          - indexType: string
            propertyName: some-str-prop
          - indexType: boolean
            propertyName: some-bool-prop
      properties:
        metadataIndexes:
          description: Array of indexed metadata properties.
          items:
            properties:
              indexType:
                description: Specifies the type of indexed metadata property.
                enum:
                  - string
                  - number
                  - boolean
                type: string
                x-auditable: true
              propertyName:
                description: Specifies the indexed metadata property.
                example: random_metadata_property
                type: string
                x-auditable: true
            type: object
          type: array
      type: object
