openapi: 3.0.3
info:
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience.


    To get started using Cloudflare's products and services via the API, refer
    to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows
    who is making requests and what permissions you have. Create an API token to
    grant access to the API to perform actions. You can also authenticate with
    [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API.


    To create an API token, from the Cloudflare dashboard, go to My Profile >
    API Tokens and select Create Token. For more information on how to create
    and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).


    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: Cloudflare API
  version: 4.0.0
servers:
  - description: Client API
    url: https://api.cloudflare.com/client/v4
paths:
  /zones/{zone_id}/settings:
    get:
      deprecated: true
      description: Available settings for your user in relation to a zone.
      operationId: zone-settings-get-all-zone-settings
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zones_zone_settings_response_collection'
          description: Get all Zone settings response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zones_components-schemas-api-response-common-failure
          description: Get all Zone settings response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get all zone settings
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
      x-stainless-deprecation-message: >-
        This endpoint is deprecated. Zone settings should instead be managed
        individually.
    patch:
      deprecated: true
      description: Edit settings for a zone.
      operationId: zone-settings-edit-zone-settings-info
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/zones_multiple_settings'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zones_zone_settings_response_collection'
          description: Edit zone settings info response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zones_components-schemas-api-response-common-failure
          description: Edit zone settings info response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Edit multiple zone settings
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
      x-stainless-deprecation-message: >-
        This endpoint is deprecated. Zone settings should instead be managed
        individually.
  /zones/{zone_id}/settings/aegis:
    get:
      description: >-
        Aegis provides dedicated egress IPs (from Cloudflare to your origin) for
        your layer 7 WAF and CDN services. The egress IPs are reserved
        exclusively for your account so that you can increase your origin
        security by only allowing traffic from a small list of IP addresses.
      operationId: zone-cache-settings-get-aegis-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/cache-rules_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/cache-rules_zone_complex_cache_settings_response_single
                  - $ref: '#/components/schemas/cache-rules_aegis_response_value'
                type: object
          description: Get aegis setting response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cache-rules_api-response-common-failure'
          description: Get aegis setting response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get aegis setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
        - Zone Read
        - Zone Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: >-
        Aegis provides dedicated egress IPs (from Cloudflare to your origin) for
        your layer 7 WAF and CDN services. The egress IPs are reserved
        exclusively for your account so that you can increase your origin
        security by only allowing traffic from a small list of IP addresses.
      operationId: zone-cache-settings-change-aegis-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/cache-rules_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                value:
                  $ref: '#/components/schemas/cache-rules_aegis_value'
              required:
                - value
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/cache-rules_zone_complex_cache_settings_response_single
                  - $ref: '#/components/schemas/cache-rules_aegis_response_value'
                type: object
          description: Change aegis setting response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cache-rules_api-response-common-failure'
          description: Change aegis setting response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Change aegis setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /zones/{zone_id}/settings/fonts:
    get:
      description: >
        Enhance your website's font delivery with Cloudflare Fonts. Deliver
        Google Hosted fonts from your own domain,

        boost performance, and enhance user privacy. Refer to the Cloudflare
        Fonts documentation for more information.
      operationId: zone-settings-get-fonts-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/speed_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/speed_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/speed_cloudflare_fonts'
          description: Get Cloudflare Fonts setting response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/speed_api-response-common-failure'
          description: Get Cloudflare Fonts setting response failure
      security:
        - api_email: []
          api_key: []
      summary: Get Cloudflare Fonts setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: >
        Enhance your website's font delivery with Cloudflare Fonts. Deliver
        Google Hosted fonts from your own domain,

        boost performance, and enhance user privacy. Refer to the Cloudflare
        Fonts documentation for more information.
      operationId: zone-settings-change-fonts-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/speed_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                value:
                  $ref: '#/components/schemas/speed_cloudflare_fonts_value'
              required:
                - value
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/speed_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/speed_cloudflare_fonts'
          description: Change Cloudflare Fonts setting response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/speed_api-response-common-failure'
          description: Change Cloudflare Fonts setting response failure
      security:
        - api_email: []
          api_key: []
      summary: Change Cloudflare Fonts setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/settings/origin_h2_max_streams:
    get:
      description: >-
        Origin H2 Max Streams configures the max number of concurrent requests
        that Cloudflare will send within the same connection when communicating
        with the origin server, if the origin supports it. Note that if your
        origin does not support H2 multiplexing, 5xx errors may be observed,
        particularly 520s. Also note that the default value is `100` for all
        plan types except Enterprise where it is `1`. `1` means that H2
        multiplexing is disabled.
      operationId: zone-cache-settings-get-origin-h2-max-streams-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/cache-rules_identifier'
      responses:
        '200':
          content:
            application/json:
              examples:
                origin_h2_max_streams_50:
                  $ref: '#/components/examples/cache-rules_origin_h2_max_streams_50'
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/cache-rules_zone_cache_settings_response_single
                  - $ref: >-
                      #/components/schemas/cache-rules_origin_h2_max_streams_response_value
                type: object
          description: Get Origin H2 Max Streams Setting Response
        4XX:
          content:
            application/json:
              examples:
                Error:
                  $ref: '#/components/examples/cache-rules_dummy_error_response'
              schema:
                $ref: '#/components/schemas/cache-rules_api-response-common-failure'
          description: Get Origin H2 Max Streams Setting Response Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Origin H2 Max Streams Setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
        - Zone Read
        - Zone Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: >-
        Origin H2 Max Streams configures the max number of concurrent requests
        that Cloudflare will send within the same connection when communicating
        with the origin server, if the origin supports it. Note that if your
        origin does not support H2 multiplexing, 5xx errors may be observed,
        particularly 520s. Also note that the default value is `100` for all
        plan types except Enterprise where it is `1`. `1` means that H2
        multiplexing is disabled.
      operationId: zone-cache-settings-change-origin-h2-max-streams-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/cache-rules_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                value:
                  $ref: '#/components/schemas/cache-rules_origin_h2_max_streams_value'
              required:
                - value
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              examples:
                origin_h2_max_streams_50:
                  $ref: '#/components/examples/cache-rules_origin_h2_max_streams_50'
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/cache-rules_zone_cache_settings_response_single
                  - $ref: >-
                      #/components/schemas/cache-rules_origin_h2_max_streams_response_value
                type: object
          description: Change Origin H2 Max Streams Setting Response
        4XX:
          content:
            application/json:
              examples:
                Error:
                  $ref: '#/components/examples/cache-rules_dummy_error_response'
              schema:
                $ref: '#/components/schemas/cache-rules_api-response-common-failure'
          description: Change Origin H2 Max Streams Response Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Change Origin H2 Max Streams Setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /zones/{zone_id}/settings/origin_max_http_version:
    get:
      description: >-
        Origin Max HTTP Setting Version sets the highest HTTP version Cloudflare
        will attempt to use with your origin. This setting allows Cloudflare to
        make HTTP/2 requests to your origin. (Refer to [Enable HTTP/2 to
        Origin](https://developers.cloudflare.com/cache/how-to/enable-http2-to-origin/),
        for more information.). The default value is "2" for all plan types
        except Enterprise where it is "1"
      operationId: zone-cache-settings-get-origin-max-http-version-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/cache-rules_identifier'
      responses:
        '200':
          content:
            application/json:
              examples:
                max_http_version_2:
                  $ref: '#/components/examples/cache-rules_origin_max_http_version_2'
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/cache-rules_zone_cache_settings_response_single
                  - $ref: >-
                      #/components/schemas/cache-rules_origin_max_http_version_response_value
                type: object
          description: Get Origin Max HTTP Version Setting Response
        4XX:
          content:
            application/json:
              examples:
                Error:
                  $ref: '#/components/examples/cache-rules_dummy_error_response'
              schema:
                $ref: '#/components/schemas/cache-rules_api-response-common-failure'
          description: Get Origin Max HTTP Version Setting Response Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Origin Max HTTP Version Setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
        - Zone Read
        - Zone Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: >-
        Origin Max HTTP Setting Version sets the highest HTTP version Cloudflare
        will attempt to use with your origin. This setting allows Cloudflare to
        make HTTP/2 requests to your origin. (Refer to [Enable HTTP/2 to
        Origin](https://developers.cloudflare.com/cache/how-to/enable-http2-to-origin/),
        for more information.). The default value is "2" for all plan types
        except Enterprise where it is "1"
      operationId: zone-cache-settings-change-origin-max-http-version-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/cache-rules_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                value:
                  $ref: >-
                    #/components/schemas/cache-rules_origin_max_http_version_value
              required:
                - value
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              examples:
                max_http_version_2:
                  $ref: '#/components/examples/cache-rules_origin_max_http_version_2'
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/cache-rules_zone_cache_settings_response_single
                  - $ref: >-
                      #/components/schemas/cache-rules_origin_max_http_version_response_value
                type: object
          description: Change Origin Max HTTP Version Setting Response
        4XX:
          content:
            application/json:
              examples:
                Error:
                  $ref: '#/components/examples/cache-rules_dummy_error_response'
              schema:
                $ref: '#/components/schemas/cache-rules_api-response-common-failure'
          description: Change Origin Max HTTP Version Response Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Change Origin Max HTTP Version Setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/settings/speed_brain:
    get:
      description: >
        Speed Brain lets compatible browsers speculate on content which can be
        prefetched or preloaded, making website

        navigation faster. Refer to the Cloudflare Speed Brain documentation for
        more information.
      operationId: zone-settings-get-speed-brain-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/speed_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/speed_api-response-common'
                  - properties:
                      result:
                        $ref: >-
                          #/components/schemas/speed_cloudflare_speed_brain_response
          description: Get Cloudflare Speed Brain setting response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/speed_api-response-common-failure'
          description: Get Cloudflare Speed Brain setting response failure
      security:
        - api_email: []
          api_key: []
      summary: Get Cloudflare Speed Brain setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: >
        Speed Brain lets compatible browsers speculate on content which can be
        prefetched or preloaded, making website

        navigation faster. Refer to the Cloudflare Speed Brain documentation for
        more information.
      operationId: zone-settings-change-speed-brain-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/speed_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                value:
                  description: Whether the feature is enabled or disabled.
                  enum:
                    - 'on'
                    - 'off'
                  type: string
              required:
                - value
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/speed_api-response-common'
                  - properties:
                      result:
                        $ref: >-
                          #/components/schemas/speed_cloudflare_speed_brain_response
          description: Cloudflare Speed Brain setting response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/speed_api-response-common-failure'
          description: Change Cloudflare Speed Brain setting response failure
      security:
        - api_email: []
          api_key: []
      summary: Change Cloudflare Speed Brain setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /zones/{zone_id}/settings/{setting_id}:
    get:
      description: Fetch a single zone setting by name
      operationId: zone-settings-get-single-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_identifier'
        - in: path
          name: setting_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_setting_name'
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zones_settings-api_components-schemas-api-response-common
                  - properties:
                      result:
                        $ref: '#/components/schemas/zones_setting'
          description: Get zone setting response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zones_components-schemas-api-response-common-failure
          description: Get zone setting response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get zone setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: false
    patch:
      description: Updates a single zone setting by the identifier
      operationId: zone-settings-edit-single-setting
      parameters:
        - in: path
          name: zone_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_identifier'
        - in: path
          name: setting_id
          required: true
          schema:
            $ref: '#/components/schemas/zones_setting_name'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/zones_zone_settings_single_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: >-
                      #/components/schemas/zones_settings-api_components-schemas-api-response-common
                  - properties:
                      result:
                        $ref: '#/components/schemas/zones_setting'
          description: Edit zone setting response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/zones_components-schemas-api-response-common-failure
          description: Edit zone settings info response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Edit zone setting
      tags:
        - Zone Settings
      x-api-token-group:
        - Zone Settings Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    cache-rules_aegis_response_value:
      properties:
        result:
          $ref: '#/components/schemas/cache-rules_aegis'
      type: object
    cache-rules_aegis_value:
      description: Value of the zone setting.
      properties:
        enabled:
          description: Whether the feature is enabled or not.
          type: boolean
          x-auditable: true
        pool_id:
          description: >-
            Egress pool id which refers to a grouping of dedicated egress IPs
            through which Cloudflare will connect to origin.
          example: pool-id
          type: string
          x-auditable: true
      type: object
    cache-rules_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/cache-rules_messages'
          example:
            - code: 7003
              message: No route for the URI
          items:
            type: object
          minLength: 1
          type: array
        messages:
          allOf:
            - $ref: '#/components/schemas/cache-rules_messages'
          example: []
          items:
            type: object
          type: array
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    cache-rules_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
      x-auditable: true
    cache-rules_origin_h2_max_streams_response_value:
      properties:
        result:
          $ref: '#/components/schemas/cache-rules_origin_h2_max_streams'
      type: object
    cache-rules_origin_h2_max_streams_value:
      description: Value of the Origin H2 Max Streams Setting.
      example: 50
      maximum: 1000
      minimum: 1
      type: integer
      x-auditable: true
    cache-rules_origin_max_http_version_response_value:
      properties:
        result:
          $ref: '#/components/schemas/cache-rules_origin_max_http_version'
      type: object
    cache-rules_origin_max_http_version_value:
      description: Value of the Origin Max HTTP Version Setting.
      enum:
        - '2'
        - '1'
      type: string
      x-auditable: true
    cache-rules_zone_cache_settings_response_single:
      allOf:
        - $ref: '#/components/schemas/cache-rules_api-response-common'
        - properties:
            result:
              $ref: '#/components/schemas/cache-rules_result-object'
          type: object
      type: object
    cache-rules_zone_complex_cache_settings_response_single:
      allOf:
        - $ref: '#/components/schemas/cache-rules_api-response-common'
        - properties:
            result:
              $ref: '#/components/schemas/cache-rules_result-object-complex'
          type: object
      type: object
    speed_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/speed_messages'
        messages:
          $ref: '#/components/schemas/speed_messages'
        success:
          description: Whether the API call was successful
          example: true
          type: boolean
          x-auditable: true
      required:
        - success
        - errors
        - messages
      type: object
    speed_api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/speed_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/speed_messages'
          example: []
        result:
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          example: false
          type: boolean
          x-auditable: true
      required:
        - success
        - errors
        - messages
        - result
      type: object
    speed_cloudflare_fonts:
      allOf:
        - $ref: '#/components/schemas/speed_base'
        - properties:
            id:
              description: ID of the zone setting.
              enum:
                - fonts
              example: fonts
              x-auditable: true
            value:
              $ref: '#/components/schemas/speed_cloudflare_fonts_value'
      description: >
        Enhance your website's font delivery with Cloudflare Fonts. Deliver
        Google Hosted fonts from your own domain,

        boost performance, and enhance user privacy. Refer to the Cloudflare
        Fonts documentation for more information.
      title: Cloudflare Fonts
    speed_cloudflare_fonts_value:
      default: 'off'
      description: Whether the feature is enabled or disabled.
      enum:
        - 'on'
        - 'off'
      type: string
      x-auditable: true
    speed_cloudflare_speed_brain_response:
      allOf:
        - $ref: '#/components/schemas/speed_base'
      properties:
        value:
          description: |
            Whether the feature is enabled or disabled.
            Defaults to "on" for Free plans, otherwise defaults to "off".
      title: Cloudflare Speed Brain response
    speed_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
      x-auditable: true
    zones_components-schemas-api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/zones_messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/zones_messages'
          example: []
        result:
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    zones_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    zones_multiple_settings:
      items:
        anyOf:
          - $ref: '#/components/schemas/zones_0rtt'
          - $ref: '#/components/schemas/zones_advanced_ddos'
          - $ref: '#/components/schemas/zones_cache-rules_aegis'
          - $ref: '#/components/schemas/zones_always_online'
          - $ref: '#/components/schemas/zones_schemas-always_use_https'
          - $ref: '#/components/schemas/zones_schemas-automatic_https_rewrites'
          - $ref: '#/components/schemas/zones_brotli'
          - $ref: '#/components/schemas/zones_schemas-browser_cache_ttl'
          - $ref: '#/components/schemas/zones_schemas-browser_check'
          - $ref: '#/components/schemas/zones_schemas-cache_level'
          - $ref: '#/components/schemas/zones_challenge_ttl'
          - $ref: '#/components/schemas/zones_china_network_enabled'
          - $ref: '#/components/schemas/zones_ciphers'
          - $ref: '#/components/schemas/zones_cname_flattening'
          - $ref: '#/components/schemas/zones_development_mode'
          - $ref: '#/components/schemas/zones_early_hints'
          - $ref: '#/components/schemas/zones_schemas-edge_cache_ttl'
          - $ref: '#/components/schemas/zones_schemas-email_obfuscation'
          - $ref: '#/components/schemas/zones_h2_prioritization'
          - $ref: '#/components/schemas/zones_hotlink_protection'
          - $ref: '#/components/schemas/zones_http2'
          - $ref: '#/components/schemas/zones_http3'
          - $ref: '#/components/schemas/zones_schemas-ip_geolocation'
          - $ref: '#/components/schemas/zones_ipv6'
          - $ref: '#/components/schemas/zones_max_upload'
          - $ref: '#/components/schemas/zones_min_tls_version'
          - $ref: '#/components/schemas/zones_schemas-mirage'
          - $ref: '#/components/schemas/zones_nel'
          - $ref: '#/components/schemas/zones_schemas-opportunistic_encryption'
          - $ref: '#/components/schemas/zones_opportunistic_onion'
          - $ref: '#/components/schemas/zones_orange_to_orange'
          - $ref: '#/components/schemas/zones_schemas-origin_error_page_pass_thru'
          - $ref: '#/components/schemas/zones_cache-rules_origin_h2_max_streams'
          - $ref: '#/components/schemas/zones_cache-rules_origin_max_http_version'
          - $ref: '#/components/schemas/zones_schemas-polish'
          - $ref: '#/components/schemas/zones_prefetch_preload'
          - $ref: '#/components/schemas/zones_privacy_pass'
          - $ref: '#/components/schemas/zones_proxy_read_timeout'
          - $ref: '#/components/schemas/zones_pseudo_ipv4'
          - $ref: '#/components/schemas/zones_replace_insecure_js'
          - $ref: '#/components/schemas/zones_schemas-response_buffering'
          - $ref: '#/components/schemas/zones_schemas-rocket_loader'
          - $ref: '#/components/schemas/zones_schemas-automatic_platform_optimization'
          - $ref: '#/components/schemas/zones_security_header'
          - $ref: '#/components/schemas/zones_schemas-security_level'
          - $ref: '#/components/schemas/zones_server_side_exclude'
          - $ref: '#/components/schemas/zones_sha1_support'
          - $ref: '#/components/schemas/zones_schemas-sort_query_string_for_cache'
          - $ref: '#/components/schemas/zones_schemas-ssl'
          - $ref: '#/components/schemas/zones_ssl_recommender'
          - $ref: '#/components/schemas/zones_tls_1_2_only'
          - $ref: '#/components/schemas/zones_tls_1_3'
          - $ref: '#/components/schemas/zones_tls_client_auth'
          - $ref: '#/components/schemas/zones_schemas-true_client_ip_header'
          - $ref: '#/components/schemas/zones_schemas-waf'
          - $ref: '#/components/schemas/zones_webp'
          - $ref: '#/components/schemas/zones_websockets'
      type: array
    zones_setting:
      oneOf:
        - $ref: '#/components/schemas/zones_0rtt'
        - $ref: '#/components/schemas/zones_advanced_ddos'
        - $ref: '#/components/schemas/zones_cache-rules_aegis'
        - $ref: '#/components/schemas/zones_always_online'
        - $ref: '#/components/schemas/zones_schemas-always_use_https'
        - $ref: '#/components/schemas/zones_schemas-automatic_https_rewrites'
        - $ref: '#/components/schemas/zones_brotli'
        - $ref: '#/components/schemas/zones_schemas-browser_cache_ttl'
        - $ref: '#/components/schemas/zones_schemas-browser_check'
        - $ref: '#/components/schemas/zones_schemas-cache_level'
        - $ref: '#/components/schemas/zones_challenge_ttl'
        - $ref: '#/components/schemas/zones_china_network_enabled'
        - $ref: '#/components/schemas/zones_ciphers'
        - $ref: '#/components/schemas/zones_cname_flattening'
        - $ref: '#/components/schemas/zones_development_mode'
        - $ref: '#/components/schemas/zones_early_hints'
        - $ref: '#/components/schemas/zones_schemas-edge_cache_ttl'
        - $ref: '#/components/schemas/zones_schemas-email_obfuscation'
        - $ref: '#/components/schemas/zones_h2_prioritization'
        - $ref: '#/components/schemas/zones_hotlink_protection'
        - $ref: '#/components/schemas/zones_http2'
        - $ref: '#/components/schemas/zones_http3'
        - $ref: '#/components/schemas/zones_image_resizing'
        - $ref: '#/components/schemas/zones_schemas-ip_geolocation'
        - $ref: '#/components/schemas/zones_ipv6'
        - $ref: '#/components/schemas/zones_max_upload'
        - $ref: '#/components/schemas/zones_min_tls_version'
        - $ref: '#/components/schemas/zones_schemas-mirage'
        - $ref: '#/components/schemas/zones_nel'
        - $ref: '#/components/schemas/zones_schemas-opportunistic_encryption'
        - $ref: '#/components/schemas/zones_opportunistic_onion'
        - $ref: '#/components/schemas/zones_orange_to_orange'
        - $ref: '#/components/schemas/zones_schemas-origin_error_page_pass_thru'
        - $ref: '#/components/schemas/zones_cache-rules_origin_h2_max_streams'
        - $ref: '#/components/schemas/zones_cache-rules_origin_max_http_version'
        - $ref: '#/components/schemas/zones_schemas-polish'
        - $ref: '#/components/schemas/zones_prefetch_preload'
        - $ref: '#/components/schemas/zones_privacy_pass'
        - $ref: '#/components/schemas/zones_proxy_read_timeout'
        - $ref: '#/components/schemas/zones_pseudo_ipv4'
        - $ref: '#/components/schemas/zones_replace_insecure_js'
        - $ref: '#/components/schemas/zones_schemas-response_buffering'
        - $ref: '#/components/schemas/zones_schemas-rocket_loader'
        - $ref: '#/components/schemas/zones_schemas-automatic_platform_optimization'
        - $ref: '#/components/schemas/zones_security_header'
        - $ref: '#/components/schemas/zones_schemas-security_level'
        - $ref: '#/components/schemas/zones_server_side_exclude'
        - $ref: '#/components/schemas/zones_sha1_support'
        - $ref: '#/components/schemas/zones_schemas-sort_query_string_for_cache'
        - $ref: '#/components/schemas/zones_schemas-ssl'
        - $ref: '#/components/schemas/zones_ssl_recommender'
        - $ref: '#/components/schemas/zones_tls_1_2_only'
        - $ref: '#/components/schemas/zones_tls_1_3'
        - $ref: '#/components/schemas/zones_tls_client_auth'
        - $ref: '#/components/schemas/zones_transformations'
        - $ref: '#/components/schemas/zones_transformations_allowed_origins'
        - $ref: '#/components/schemas/zones_schemas-true_client_ip_header'
        - $ref: '#/components/schemas/zones_schemas-waf'
        - $ref: '#/components/schemas/zones_webp'
        - $ref: '#/components/schemas/zones_websockets'
      type: object
    zones_setting_name:
      description: Setting name
      example: always_online
      type: string
    zones_settings-api_components-schemas-api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/zones_messages'
        messages:
          $ref: '#/components/schemas/zones_messages'
        success:
          description: Whether the API call was successful
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
      type: object
    zones_zone_settings_response_collection:
      allOf:
        - $ref: >-
            #/components/schemas/zones_settings-api_components-schemas-api-response-common
        - properties:
            result:
              items:
                anyOf:
                  - $ref: '#/components/schemas/zones_0rtt'
                  - $ref: '#/components/schemas/zones_advanced_ddos'
                  - $ref: '#/components/schemas/zones_cache-rules_aegis'
                  - $ref: '#/components/schemas/zones_always_online'
                  - $ref: '#/components/schemas/zones_schemas-always_use_https'
                  - $ref: >-
                      #/components/schemas/zones_schemas-automatic_https_rewrites
                  - $ref: '#/components/schemas/zones_brotli'
                  - $ref: '#/components/schemas/zones_schemas-browser_cache_ttl'
                  - $ref: '#/components/schemas/zones_schemas-browser_check'
                  - $ref: '#/components/schemas/zones_schemas-cache_level'
                  - $ref: '#/components/schemas/zones_challenge_ttl'
                  - $ref: '#/components/schemas/zones_ciphers'
                  - $ref: '#/components/schemas/zones_cname_flattening'
                  - $ref: '#/components/schemas/zones_development_mode'
                  - $ref: '#/components/schemas/zones_early_hints'
                  - $ref: '#/components/schemas/zones_schemas-edge_cache_ttl'
                  - $ref: '#/components/schemas/zones_schemas-email_obfuscation'
                  - $ref: '#/components/schemas/zones_h2_prioritization'
                  - $ref: '#/components/schemas/zones_hotlink_protection'
                  - $ref: '#/components/schemas/zones_http2'
                  - $ref: '#/components/schemas/zones_http3'
                  - $ref: '#/components/schemas/zones_image_resizing'
                  - $ref: '#/components/schemas/zones_schemas-ip_geolocation'
                  - $ref: '#/components/schemas/zones_ipv6'
                  - $ref: '#/components/schemas/zones_max_upload'
                  - $ref: '#/components/schemas/zones_min_tls_version'
                  - $ref: '#/components/schemas/zones_schemas-mirage'
                  - $ref: '#/components/schemas/zones_nel'
                  - $ref: >-
                      #/components/schemas/zones_schemas-opportunistic_encryption
                  - $ref: '#/components/schemas/zones_opportunistic_onion'
                  - $ref: '#/components/schemas/zones_orange_to_orange'
                  - $ref: >-
                      #/components/schemas/zones_schemas-origin_error_page_pass_thru
                  - $ref: >-
                      #/components/schemas/zones_cache-rules_origin_h2_max_streams
                  - $ref: >-
                      #/components/schemas/zones_cache-rules_origin_max_http_version
                  - $ref: '#/components/schemas/zones_schemas-polish'
                  - $ref: '#/components/schemas/zones_prefetch_preload'
                  - $ref: '#/components/schemas/zones_privacy_pass'
                  - $ref: '#/components/schemas/zones_proxy_read_timeout'
                  - $ref: '#/components/schemas/zones_pseudo_ipv4'
                  - $ref: '#/components/schemas/zones_replace_insecure_js'
                  - $ref: '#/components/schemas/zones_schemas-response_buffering'
                  - $ref: '#/components/schemas/zones_schemas-rocket_loader'
                  - $ref: >-
                      #/components/schemas/zones_schemas-automatic_platform_optimization
                  - $ref: '#/components/schemas/zones_security_header'
                  - $ref: '#/components/schemas/zones_schemas-security_level'
                  - $ref: '#/components/schemas/zones_server_side_exclude'
                  - $ref: '#/components/schemas/zones_sha1_support'
                  - $ref: >-
                      #/components/schemas/zones_schemas-sort_query_string_for_cache
                  - $ref: '#/components/schemas/zones_schemas-ssl'
                  - $ref: '#/components/schemas/zones_ssl_recommender'
                  - $ref: '#/components/schemas/zones_tls_1_2_only'
                  - $ref: '#/components/schemas/zones_tls_1_3'
                  - $ref: '#/components/schemas/zones_tls_client_auth'
                  - $ref: '#/components/schemas/zones_transformations'
                  - $ref: '#/components/schemas/zones_transformations_allowed_origins'
                  - $ref: '#/components/schemas/zones_schemas-true_client_ip_header'
                  - $ref: '#/components/schemas/zones_schemas-waf'
                  - $ref: '#/components/schemas/zones_webp'
                  - $ref: '#/components/schemas/zones_websockets'
              type: array
    zones_zone_settings_single_request:
      oneOf:
        - properties:
            enabled:
              $ref: '#/components/schemas/zones_ssl_recommender_enabled'
          type: object
        - properties:
            value:
              $ref: '#/components/schemas/zones_setting_value'
          type: object
  examples:
    cache-rules_dummy_error_response:
      value:
        errors:
          - code: 12345
            message: Some error message
        messages: []
        result: null
        success: false
    cache-rules_origin_h2_max_streams_50:
      value:
        errors: []
        messages: []
        result:
          editable: true
          id: origin_h2_max_streams
          value: 50
        success: true
    cache-rules_origin_max_http_version_2:
      value:
        errors: []
        messages: []
        result:
          editable: true
          id: origin_max_http_version
          value: '2'
        success: true
